FROM node:lts-alpine@sha256:7a91aa397f2e2dfbfcdad2e2d72599f374e0b0172be1d86eeb73f1d33f36a4b2
RUN apk --no-cache -U upgrade && apk add --no-cache python3 make g++
WORKDIR /usr/src/app
VOLUME /usr/src/app
