FROM node:lts-alpine@sha256:58878e9e1ed3911bdd675d576331ed8838fc851607aed3bb91e25dfaffab3267
RUN apk --no-cache -U upgrade && apk add --no-cache python3 make g++
WORKDIR /usr/src/app
VOLUME /usr/src/app
