FROM node:lts-alpine@sha256:8e015de364a2eb2ed7c52a558e9f716dcb615560ffd132234087c10ccc1f2c63
RUN apk --no-cache -U upgrade && apk add --no-cache python3 make g++
WORKDIR /usr/src/app
VOLUME /usr/src/app
